export const KEYBINDING_CONFIG = {
  quit: ["q"],
  emergencyStop: ["!"],
  help: ["?"],
  commandPalette: ["/", "p", "ctrl+p", "ctrl+shift+p"],
  toggleSidebar: ["ctrl+b"],
  openSettings: ["ctrl+,"],
  focusNext: ["tab"],
  focusPrevious: ["shift+tab"],
  areaNext: ["ctrl+tab"],
  areaPrevious: ["ctrl+shift+tab"],
  cancel: ["escape"],
  activate: ["enter"],
  toggleSelection: ["space"],
  previous: ["up"],
  next: ["down"],
  previousVim: ["k"],
  nextVim: ["j"],
  previousPanel: ["left"],
  nextPanel: ["right"],
  create: ["n"],
  edit: ["e"],
  archive: ["d"],
  restore: ["u"],
  run: ["r"],
  verify: ["v"],
  nextTheme: ["t"],
  previousRecord: ["["],
  nextRecord: ["]"],
  confirm: ["y"],
  showAdvanced: ["ctrl+a"],
} as const;
