import { randomUUID } from "node:crypto";
import { totalmem, freemem } from "node:os";
import type { AuditRepository } from "../storage/audit-repository.js";
import { AttemptRepository } from "./attempt-repository.js";
import type { AttemptRecord, AttemptRequest, AttemptResult } from "./attempt-types.js";
import { CapacityController } from "./capacity-controller.js";
import type { DockerClient } from "./docker-client.js";
import type { ResourceSnapshot } from "./types.js";
import { engineAdapter } from "../engines/engine-adapter.js";
import type { ArtifactRecord } from "../acceptance/artifact-types.js";
import type { ExecutionEvidenceRepository } from "../storage/execution-evidence-repository.js";

export interface AttemptFinalizer {
  finalize(attempt: AttemptRecord, secrets: Record<string, string>): Promise<ArtifactRecord[]>;
}

export class DockerSupervisor {
  readonly ownerId = randomUUID();
  private readonly running = new Map<string, Promise<void>>();
  private stopped = false;

  constructor(
    readonly attempts: AttemptRepository,
    private readonly docker: DockerClient,
    private readonly audit: AuditRepository,
    private readonly capacity = new CapacityController(2),
    private readonly resources: (running: number) => ResourceSnapshot = (running) => ({
      totalMemoryMb: Math.floor(totalmem() / 1_048_576),
      availableMemoryMb: Math.floor(freemem() / 1_048_576),
      running,
    }),
    private readonly secretProvider: (attempt: AttemptRecord) => Record<string, string> = (
      attempt,
    ) => {
      if (attempt.secretNames.length > 0)
        throw new Error("Attempt secrets require an authorized provider");
      return {};
    },
    private readonly finalizer?: AttemptFinalizer,
    private readonly evidence?: ExecutionEvidenceRepository,
  ) {}

  enqueue(request: AttemptRequest): AttemptRecord {
    if (this.stopped) throw new Error("Supervisor emergency stop is active");
    const adapter = engineAdapter(request.sandbox.engine);
    const expected = adapter.executionCommand({
      engine: request.sandbox.engine,
      model: request.command[3] ?? "",
      objective: request.command[4] ?? "",
    });
    if (
      request.command.length !== expected.length ||
      request.command.some((item, index) => item !== expected[index])
    )
      throw new Error("Attempt command must be generated by the selected engine adapter");
    return this.attempts.enqueue(request);
  }

  async tick(): Promise<void> {
    if (this.stopped) return;
    if (!(await this.docker.available())) {
      for (const attempt of this.attempts.queued(100))
        this.attempts.setStatus(attempt.id, "infrastructure-blocked", {
          reason: "Docker unavailable",
        });
      return;
    }
    const decision = this.capacity.decide(this.resources(this.running.size));
    for (const attempt of this.attempts.queued(decision.availableSlots)) this.launch(attempt);
  }

  async waitForIdle(): Promise<void> {
    while (this.running.size > 0) await Promise.all([...this.running.values()]);
  }

  async emergencyStop(actorId: string): Promise<void> {
    this.stopped = true;
    const active = this.attempts.active();
    await Promise.all(active.map((attempt) => this.docker.stop(attempt.containerName)));
    for (const attempt of active)
      this.attempts.setStatus(attempt.id, "interrupted", {
        reason: `Emergency stop by ${actorId}`,
      });
    for (const companyId of new Set(active.map(({ companyId }) => companyId)))
      this.audit.append("supervisor.emergency-stop", actorId, companyId, {
        attempts: active.map(({ id }) => id),
      });
  }

  async reconcile(): Promise<{ recoveredLeases: string[]; removedOrphans: string[] }> {
    if (!(await this.docker.available())) return { recoveredLeases: [], removedOrphans: [] };
    const recoveredLeases = this.attempts.clearExpiredLeases();
    const expected = new Set(this.attempts.active().map(({ containerName }) => containerName));
    const managed = await this.docker.managedContainers();
    const removedOrphans = managed.filter((name) => !expected.has(name));
    await Promise.all(removedOrphans.map((name) => this.docker.removeContainer(name)));
    return { recoveredLeases, removedOrphans };
  }

  private launch(attempt: AttemptRecord): void {
    this.attempts.acquire(attempt, this.ownerId);
    const operation = this.run(attempt).finally(async () => {
      this.running.delete(attempt.id);
      if (!this.stopped) await this.tick();
    });
    this.running.set(attempt.id, operation);
  }

  private async run(attempt: AttemptRecord): Promise<void> {
    try {
      await this.docker.createVolume(attempt.sandbox.workspace.name);
      this.attempts.setStatus(attempt.id, "running");
      const secrets = this.secretProvider(attempt);
      if (Object.keys(secrets).some((name) => !attempt.secretNames.includes(name)))
        throw new Error("Secret provider returned an undeclared secret");
      const result = await this.docker.start(attempt.sandbox, attempt.id, attempt.command, secrets);
      await this.recordResult(attempt, result, secrets);
    } catch (error) {
      const reason = error instanceof Error ? error.message : "Unknown Docker failure";
      this.attempts.setStatus(attempt.id, "infrastructure-blocked", { reason });
      await this.docker.stop(attempt.containerName);
    }
  }

  private async recordResult(
    attempt: AttemptRecord,
    result: AttemptResult,
    secrets: Record<string, string>,
  ): Promise<void> {
    const safeResult = redactResult(result, Object.values(secrets));
    this.evidence?.rawEvent(attempt.id, "container", {
      exitCode: safeResult.exitCode,
      timedOut: safeResult.timedOut,
      stdout: safeResult.stdout,
      stderr: safeResult.stderr,
    });
    this.attempts.event(attempt.id, "container.output", {
      stdout: safeResult.stdout,
      stderr: safeResult.stderr,
    });
    if (result.timedOut)
      this.attempts.setStatus(attempt.id, "timed-out", {
        exitCode: result.exitCode,
        reason: "Attempt timeout",
      });
    else if (result.exitCode !== 0)
      this.attempts.setStatus(attempt.id, "failed", {
        exitCode: result.exitCode,
        reason: "Container exited non-zero",
      });
    else {
      let artifacts: ArtifactRecord[];
      try {
        artifacts = this.finalizer ? await this.finalizer.finalize(attempt, secrets) : [];
      } catch (error) {
        this.attempts.setStatus(attempt.id, "failed", {
          exitCode: result.exitCode,
          reason: error instanceof Error ? error.message : "Artifact validation failed",
        });
        return;
      }
      this.evidence?.activity({
        companyId: attempt.companyId,
        taskId: attempt.taskId,
        attemptId: attempt.id,
        kind: "attempt.completed",
        summary: `Attempt completed with ${artifacts.length} validated artifacts`,
        evidenceIds: artifacts.map(({ id }) => id),
      });
      this.attempts.setStatus(attempt.id, "succeeded", { exitCode: result.exitCode });
    }
  }
}

function redactResult(result: AttemptResult, secrets: string[]): AttemptResult {
  const redact = (value: string): string =>
    secrets.filter(Boolean).reduce((safe, secret) => safe.replaceAll(secret, "[REDACTED]"), value);
  return { ...result, stdout: redact(result.stdout), stderr: redact(result.stderr) };
}
