import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { Employee, WorkforceEvent } from "./domain.js";

export interface CompanyRecord { id:string; name:string; displayName:string; mission:string; vision:string; values:string[]; policies:Record<string,unknown>; budgetCents:number; createdAt:string }
export interface EntityRecord { id:string; companyId:string; kind:string; parentId:string|null; name:string; status:string; data:Record<string,unknown>; createdAt:string; updatedAt:string }
export interface MessageRecord { id:string; companyId:string; roomId:string; threadId:string|null; authorId:string; body:string; createdAt:string; pinned:boolean }

const schema = `
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS companies(id TEXT PRIMARY KEY,name TEXT NOT NULL,display_name TEXT NOT NULL,mission TEXT NOT NULL DEFAULT '',vision TEXT NOT NULL DEFAULT '',values_json TEXT NOT NULL DEFAULT '[]',policies_json TEXT NOT NULL DEFAULT '{}',budget_cents INTEGER NOT NULL DEFAULT 0 CHECK(budget_cents>=0),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS employees(id TEXT NOT NULL,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,name TEXT NOT NULL,title TEXT NOT NULL,role TEXT NOT NULL,department TEXT NOT NULL,manager_id TEXT,status TEXT NOT NULL,responsibilities_json TEXT NOT NULL,capabilities_json TEXT NOT NULL,hired_at TEXT NOT NULL,PRIMARY KEY(company_id,id),FOREIGN KEY(company_id,manager_id) REFERENCES employees(company_id,id));
CREATE TABLE IF NOT EXISTS entities(id TEXT NOT NULL,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,kind TEXT NOT NULL,parent_id TEXT,name TEXT NOT NULL,status TEXT NOT NULL,data_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(company_id,id),FOREIGN KEY(company_id,parent_id) REFERENCES entities(company_id,id));
CREATE INDEX IF NOT EXISTS entities_company_kind ON entities(company_id,kind,status);
CREATE TABLE IF NOT EXISTS rooms(id TEXT NOT NULL,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,name TEXT NOT NULL,kind TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(company_id,id));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,company_id TEXT NOT NULL,room_id TEXT NOT NULL,thread_id TEXT,author_id TEXT NOT NULL,body TEXT NOT NULL,pinned INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,FOREIGN KEY(company_id,room_id) REFERENCES rooms(company_id,id));
CREATE INDEX IF NOT EXISTS messages_room_time ON messages(company_id,room_id,created_at DESC);
CREATE TABLE IF NOT EXISTS events(sequence INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,at TEXT NOT NULL,type TEXT NOT NULL,actor TEXT NOT NULL,company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,data_json TEXT NOT NULL,previous_hash TEXT NOT NULL,hash TEXT UNIQUE NOT NULL);
CREATE INDEX IF NOT EXISTS events_company_sequence ON events(company_id,sequence DESC);
CREATE TABLE IF NOT EXISTS approvals(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),subject_type TEXT NOT NULL,subject_id TEXT NOT NULL,requested_by TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected')),rationale TEXT NOT NULL DEFAULT '',decided_by TEXT,created_at TEXT NOT NULL,decided_at TEXT);
CREATE INDEX IF NOT EXISTS approvals_pending ON approvals(company_id,status,created_at);
CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),subject_type TEXT NOT NULL,subject_id TEXT NOT NULL,kind TEXT NOT NULL,uri TEXT NOT NULL,digest TEXT NOT NULL,observed_at TEXT NOT NULL,validator TEXT,valid INTEGER);
CREATE INDEX IF NOT EXISTS evidence_subject ON evidence(company_id,subject_type,subject_id);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value_json TEXT NOT NULL);`;
const parse=<T>(v:unknown):T=>JSON.parse(String(v)) as T;
export const sanitizeTerminal=(value:string,max=20_000):string=>value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F\u001B]/g,"").slice(0,max);

export class StateStore {
  readonly root:string; readonly path:string; #db:DatabaseSync|null=null;
  constructor(root=resolve(process.cwd(),".workforce")){this.root=root;this.path=resolve(root,"workforce.sqlite")}
  get db():DatabaseSync{if(!this.#db)throw new Error("StateStore is not initialized");return this.#db}
  async initialize():Promise<void>{mkdirSync(this.root,{recursive:true,mode:0o700});mkdirSync(resolve(this.root,"artifacts"),{recursive:true,mode:0o700});this.#db??=new DatabaseSync(this.path);this.db.exec("PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;");this.transaction(()=>{if(!this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='schema_migrations'").get()){this.db.exec(schema);this.db.prepare("INSERT INTO schema_migrations VALUES(1,?)").run(new Date().toISOString())}})}
  close():void{this.#db?.close();this.#db=null}
  transaction<T>(fn:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const result=fn();this.db.exec("COMMIT");return result}catch(error){this.db.exec("ROLLBACK");throw error}}
  createCompany(input:{id?:string;name:string;displayName?:string;mission?:string;vision?:string;values?:string[];policies?:Record<string,unknown>;budgetCents?:number}):CompanyRecord{
    const now=new Date().toISOString(),id=input.id??randomUUID();if(!/^[a-z0-9][a-z0-9-]{1,63}$/.test(id))throw new Error("Company id must be 2-64 lowercase letters, numbers, or hyphens");
    const c:CompanyRecord={id,name:sanitizeTerminal(input.name,200),displayName:sanitizeTerminal(input.displayName??input.name,200),mission:sanitizeTerminal(input.mission??""),vision:sanitizeTerminal(input.vision??""),values:(input.values??[]).map(v=>sanitizeTerminal(v,200)),policies:input.policies??{network:"deny-by-default",terminationApproval:"ceo"},budgetCents:input.budgetCents??0,createdAt:now};if(!c.name)throw new Error("Company name is required");
    this.transaction(()=>{this.db.prepare("INSERT INTO companies VALUES(?,?,?,?,?,?,?,?,?)").run(c.id,c.name,c.displayName,c.mission,c.vision,JSON.stringify(c.values),JSON.stringify(c.policies),c.budgetCents,now);const people:Employee[]=[{id:"ceo",name:"Chief Executive",title:"CEO Agent",role:"executive",department:"executive",team:null,manager:null,status:"active",responsibilities:["Strategy","priorities","delegation","approvals"],capabilityTags:["strategy","delegation","approval"],hiredAt:now},{id:"arm",name:"Agent Resources Manager",title:"Agent Resources Manager",role:"manager",department:"people-operations",team:null,manager:"ceo",status:"active",responsibilities:["Capacity planning","adaptive hiring","evidence-based performance","safe offboarding"],capabilityTags:["workforce-planning","hiring","governance"],hiredAt:now}];for(const p of people)this.insertEmployee(id,p);for(const room of [["ceo-office","CEO Office","private-office"],["arm-office","ARM Office","private-office"],["company-lobby","Company Lobby","company"]] as const)this.db.prepare("INSERT INTO rooms VALUES(?,?,?,?,?)").run(room[0],id,room[1],room[2],now);this.appendSync("company.created","human",id,{name:c.name})});return c
  }
  private insertEmployee(companyId:string,e:Employee):void{this.db.prepare("INSERT INTO employees VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(e.id,companyId,e.name,e.title,e.role??"contributor",e.department,e.manager,e.status,JSON.stringify(e.responsibilities),JSON.stringify(e.capabilityTags),e.hiredAt)}
  async bootstrapOrganization(id:string,name:string):Promise<Employee[]>{if(!this.company(id))this.createCompany({id,name});return this.employees(id)}
  company(id:string):CompanyRecord|undefined{const r=this.db.prepare("SELECT * FROM companies WHERE id=?").get(id) as Record<string,unknown>|undefined;return r?{id:String(r.id),name:String(r.name),displayName:String(r.display_name),mission:String(r.mission),vision:String(r.vision),values:parse(r.values_json),policies:parse(r.policies_json),budgetCents:Number(r.budget_cents),createdAt:String(r.created_at)}:undefined}
  companies():CompanyRecord[]{return(this.db.prepare("SELECT id FROM companies ORDER BY created_at").all() as {id:string}[]).map(r=>this.company(r.id)!)}
  employees(companyId:string):Employee[]{return(this.db.prepare("SELECT * FROM employees WHERE company_id=? ORDER BY hired_at").all(companyId) as Record<string,unknown>[]).map(r=>({id:String(r.id),name:String(r.name),title:String(r.title),role:String(r.role),department:String(r.department),team:null,manager:r.manager_id===null?null:String(r.manager_id),status:String(r.status) as Employee["status"],responsibilities:parse(r.responsibilities_json),capabilityTags:parse(r.capabilities_json),hiredAt:String(r.hired_at)}))}
  createEntity(companyId:string,kind:string,name:string,data:Record<string,unknown>={},parentId:string|null=null):EntityRecord{this.requireCompany(companyId);const now=new Date().toISOString(),e:EntityRecord={id:randomUUID(),companyId,kind:sanitizeTerminal(kind,40),parentId,name:sanitizeTerminal(name,200),status:"active",data,createdAt:now,updatedAt:now};this.transaction(()=>{this.db.prepare("INSERT INTO entities VALUES(?,?,?,?,?,?,?,?,?)").run(e.id,companyId,e.kind,parentId,e.name,e.status,JSON.stringify(data),now,now);this.appendSync(`${e.kind}.created`,"human",companyId,{id:e.id,name:e.name})});return e}
  entities(companyId:string,kind?:string,limit=100):EntityRecord[]{const rows=(kind?this.db.prepare("SELECT * FROM entities WHERE company_id=? AND kind=? ORDER BY updated_at DESC LIMIT ?").all(companyId,kind,limit):this.db.prepare("SELECT * FROM entities WHERE company_id=? ORDER BY updated_at DESC LIMIT ?").all(companyId,limit)) as Record<string,unknown>[];return rows.map(r=>({id:String(r.id),companyId:String(r.company_id),kind:String(r.kind),parentId:r.parent_id===null?null:String(r.parent_id),name:String(r.name),status:String(r.status),data:parse(r.data_json),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}))}
  addMessage(companyId:string,roomId:string,authorId:string,body:string,threadId:string|null=null):MessageRecord{this.requireCompany(companyId);const m:MessageRecord={id:randomUUID(),companyId,roomId,threadId,authorId:sanitizeTerminal(authorId,100),body:sanitizeTerminal(body),createdAt:new Date().toISOString(),pinned:false};this.transaction(()=>{this.db.prepare("INSERT INTO messages VALUES(?,?,?,?,?,?,?,?)").run(m.id,companyId,roomId,threadId,m.authorId,m.body,0,m.createdAt);this.appendSync("message.created",m.authorId,companyId,{messageId:m.id,roomId,threadId})});return m}
  messages(companyId:string,roomId:string,limit=100):MessageRecord[]{return(this.db.prepare("SELECT * FROM messages WHERE company_id=? AND room_id=? ORDER BY created_at DESC LIMIT ?").all(companyId,roomId,limit) as Record<string,unknown>[]).reverse().map(r=>({id:String(r.id),companyId:String(r.company_id),roomId:String(r.room_id),threadId:r.thread_id===null?null:String(r.thread_id),authorId:String(r.author_id),body:String(r.body),createdAt:String(r.created_at),pinned:Number(r.pinned)===1}))}
  requestApproval(companyId:string,subjectType:string,subjectId:string,requestedBy:string):string{this.requireCompany(companyId);const id=randomUUID(),now=new Date().toISOString();this.transaction(()=>{this.db.prepare("INSERT INTO approvals(id,company_id,subject_type,subject_id,requested_by,status,created_at) VALUES(?,?,?,?,?,'pending',?)").run(id,companyId,subjectType,subjectId,requestedBy,now);this.appendSync("approval.requested",requestedBy,companyId,{id,subjectType,subjectId})});return id}
  pendingApprovals(companyId:string):number{return Number((this.db.prepare("SELECT count(*) n FROM approvals WHERE company_id=? AND status='pending'").get(companyId) as {n:number}).n)}
  async append(type:string,actor:string,organizationId:string,data:Record<string,unknown>):Promise<WorkforceEvent>{return this.appendSync(type,actor,organizationId,data)}
  private appendSync(type:string,actor:string,companyId:string,data:Record<string,unknown>):WorkforceEvent{const prev=this.db.prepare("SELECT hash FROM events ORDER BY sequence DESC LIMIT 1").get() as {hash:string}|undefined;const event={id:randomUUID(),at:new Date().toISOString(),type:sanitizeTerminal(type,100),actor:sanitizeTerminal(actor,100),organizationId:companyId,data};const hash=createHash("sha256").update(`${prev?.hash??"GENESIS"}\n${JSON.stringify(event)}`).digest("hex");this.db.prepare("INSERT INTO events(id,at,type,actor,company_id,data_json,previous_hash,hash) VALUES(?,?,?,?,?,?,?,?)").run(event.id,event.at,event.type,event.actor,companyId,JSON.stringify(data),prev?.hash??"GENESIS",hash);return event}
  async events(companyId?:string,limit=500):Promise<WorkforceEvent[]>{const rows=(companyId?this.db.prepare("SELECT * FROM events WHERE company_id=? ORDER BY sequence DESC LIMIT ?").all(companyId,limit):this.db.prepare("SELECT * FROM events ORDER BY sequence DESC LIMIT ?").all(limit)) as Record<string,unknown>[];return rows.reverse().map(r=>({id:String(r.id),at:String(r.at),type:String(r.type),actor:String(r.actor),organizationId:String(r.company_id),data:parse(r.data_json)}))}
  verifyAuditChain():boolean{const rows=this.db.prepare("SELECT * FROM events ORDER BY sequence").all() as Record<string,unknown>[];let prev="GENESIS";for(const r of rows){const event={id:String(r.id),at:String(r.at),type:String(r.type),actor:String(r.actor),organizationId:String(r.company_id),data:parse(r.data_json)};const expected=createHash("sha256").update(`${prev}\n${JSON.stringify(event)}`).digest("hex");if(r.previous_hash!==prev||r.hash!==expected)return false;prev=String(r.hash)}return true}
  backup(target:string):void{const path=resolve(target);if(path===this.path)throw new Error("Backup target must differ from database");this.db.exec("PRAGMA wal_checkpoint(FULL)");mkdirSync(dirname(path),{recursive:true});writeFileSync(path,readFileSync(this.path),{mode:0o600})}
  private requireCompany(id:string):void{if(!this.company(id))throw new Error(`Unknown company: ${id}`)}
}
